---
- name: Create Drupal database.
  mysql_db: "db={{ drupal_mysql_database }} state=present"

- name: Create Drupal database user grant.
  mysql_user: "name={{ drupal_mysql_user }} host=% password={{ drupal_mysql_password }} priv={{ drupal_mysql_database }}.*:ALL state=present"

- name: Create Drupal database user grant.
  mysql_user: "name={{ drupal_mysql_user }} host=localhost password={{ drupal_mysql_password }} priv={{ drupal_mysql_database }}.*:ALL state=present"

- name: Remove default virtualhost file.
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  notify: restart webserver

- name: Check if Drupal is already set up.
  stat: "path={{ drupal_core_path }}"
  register: drupal_site

- name: Generate Drupal site with drush makefile.
  command: "drush make -y /vagrant/drupal.make.yml {{ drupal_core_path }}"
  when: drupal_site.stat.exists == false
  notify: restart webserver
  sudo: no

- name: Update ownership of all files within drupal_core_path.
  file:
    path: "{{ drupal_core_path }}"
    owner: vagrant
    group: www-data
    mode: 0775
    recurse: yes
